#!/bin/bash

# Author: Aidan
# Created: 6 Feb 2023
# Last Modified: 6 Feb 2023

# Description:
# Creates a backup in the current directory of all files in the home director

# Usage:
# backup_script

tar -cvf ./my_backup_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2>/dev/null

exit 0


